#!/bin/sh

usage() {
	echo "$0 <dir>"

}

if [ ! "$1" ]; then
	usage
	exit 1
fi

case "$1" in
 -h|--help) usage; exit 0;;
 --) shift;;
 -*) usage; exit 1;;
esac

while [ "$1" ]; do
	target="$1";
	if [ ! -d "$target" -a ! -f "$target" ]; then
	    echo "$target: no such file or directory"
	else
		xattr -d -r com.apple.quarantine "$target"
	fi
	shift
done
