#!/bin/sh

login="`basename $0`"

if [ $# -lt 1 ]; then
	printf "Usage:\n\t%s <host> [command] [arguments]\n" "$login" 1>&2
	exit 255;
fi

host="$1"
shift

if [ -x `which up` ]; then
	up $host
	status=$?
	if [ $status -ne 0 ]; then
		exit $status
	fi
fi

bastion=''
if [ `uname -n` != 'bastion' ]; then
	chao='ssh -t bastion'
fi

exec $chao ssh -t "$login"@"$host" "$@"
